name: Slack Notification Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "username": "GitHub-CI",
              "icon_url": "https://octodex.github.com/images/mona-the-rivetertocat.png",
              "attachments": [
                {
                  "pretext": "Triggered via {{eventName}} by {{actor}} {{or action 'action'}} {{ref}} `{{diffRef}}`",
                  "title": "GitHub Actions",
                  "title_link": "https://support.github.com",
                  "text": "*<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>",
                  "fallback": "[GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}",
                  "fields": [
                    {
                      "title": "Job Steps",
                      "value": "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}",
                      "short": false
                    },
                    {
                      "title": "Job Matrix",
                      "value": "{{#each jobMatrix}}{{@key}}: {{this}}\n{{/each}}",
                      "short": false
                    },
                    {
                      "title": "Workflow",
                      "value": "<{{workflowUrl}}|{{workflow}}>",
                      "short": true
                    },
                    {
                      "title": "Git Ref",
                      "value": "{{ref}} ({{refType}})",
                      "short": true
                    },
                    {
                      "title": "Run ID",
                      "value": "<{{workflowRunUrl}}|{{runId}}>",
                      "short": true
                    },
                    {
                      "title": "Run Number",
                      "value": "{{runNumber}}",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "{{actor}}",
                      "short": true
                    },
                    {
                      "title": "Job Status",
                      "value": "{{jobStatus}}",
                      "short": true
                    }
                  ],
                  "footer": "<{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}",
                  "color": "{{#if (eq jobStatus 'success')}}#5DADE2{{else if (eq jobStatus 'failure')}}#884EA0{{else if (eq jobStatus 'cancelled')}}#A569BD{{else}}#7D3C98{{/if}}"
                }
              ]
            }
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
