name: Web Tests

on:
  workflow_dispatch:
    inputs:
      testNames:
        description: 'Names of the tests to run (use | to separate multiple names)'
        required: false
  
permissions:
  contents: write

jobs:
  call-common-workflow:
    uses: ./.github/workflows/common-workflow.yml
    with:
      run_script: |
        npm run test:all "${{ inputs.testNames }}" 2>&1 | tee /dev/stderr
      TEST_NAMES: ${{ inputs.testNames }}

  send-slack-notification:
    runs-on: ubuntu-latest
    needs: call-common-workflow
    steps:
      - name: Debug Allure Report URL
        if: always()
        run: echo "ALLURE_REPORT_URL is ${{ needs.call-common-workflow.outputs.REPORT_URL }}"
      
      - uses: act10ns/slack@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_WEB_TESTS }}
          GITHUB_RUN_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          ALLURE_REPORT_URL: ${{ needs.call-common-workflow.outputs.REPORT_URL }}
        run: |
          STATUS="Success"
           if [ "${{ needs.call-common-workflow.result }}" != "success" ]; then
             STATUS="Failure"
          fi
           curl -X POST -H 'Content-type: application/json' \
           --data '{
             "username": "API Tests",
             "icon_emoji": ":pepe-scared:",
             "text": "*API Tests Workflow completed with status*: '"$STATUS"'\n*Environment*: '${{ inputs.environment }}'\n*Brand*: '${{ inputs.brand }}'\n*Branch*: '${{ github.ref_name }}'\n*Triggered by*: '${{ github.actor }}'\n*Run details*: <'${GITHUB_RUN_URL}'|Click here>\n*Allure Report*: <'${ALLURE_REPORT_URL}'|View Allure Report>"
           }' \
           $SLACK_WEBHOOK_URL
          config: notifications/slack.yml
        if: always()
