name: Web Tests

on:
  workflow_dispatch:
    inputs:
      testNames:
        description: 'Names of the tests to run (use | to separate multiple names)'
        required: false

permissions:
  contents: write

jobs:
  call-common-workflow:
    uses: ./.github/workflows/common-workflow.yml
    with:
      run_script: |
        npm run test:all "${{ inputs.testNames }}" 2>&1 | tee /dev/stderr
      TEST_NAMES: ${{ inputs.testNames }}

  send-slack-notification:
    runs-on: ubuntu-latest
    needs: call-common-workflow
    steps:
      - name: Download AI analysis result artifact
        uses: actions/download-artifact@v4
        with:
          name: ai-analysis-result

      - name: Read AI Analysis Result
        id: ai_result
        run: |
          echo "---------- AI Analysis Result ----------"
          cat ai_analysis_result.json
          # Zapisujemy treść do GITHUB_OUTPUT, by potem użyć jako ${{ steps.ai_result.outputs.summary }}
          SUMMARY=$(cat ai_analysis_result.json | jq -r .)
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_WEB_TESTS }}
          GITHUB_RUN_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          ALLURE_REPORT_URL: ${{ needs.call-common-workflow.outputs.REPORT_URL }}
        run: |
          STATUS="Success"
          if [ "${{ needs.call-common-workflow.result }}" != "success" ]; then
            STATUS="Failure"
          fi
          AI_SUMMARY=$(cat ai_analysis_result.json)
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "username": "AI Test Bot",
            "icon_emoji": ":robot_face:",
            "text": "*API Tests Workflow completed with status*: '"$STATUS"'\n*Branch*: '${{ github.ref_name }}'\n*Triggered by*: '${{ github.actor }}'\n*Run details*: <'${GITHUB_RUN_URL}'|Click here>\n*Allure Report*: <'${ALLURE_REPORT_URL}'|View Allure Report>\n\n*AI Analysis Summary*: ```'"$AI_SUMMARY"'```"
          }' \
          $SLACK_WEBHOOK_URL

      # (Opcjonalnie) wysyłka maila, jeśli masz skonfigurowane narzędzie/API do wysyłania emaili
      # Poniżej przykład prostego CLI mail (musisz mieć skonfigurowanego mailx / mailutils na runnerze)
      - name: Send Email with AI Analysis and Allure Report
        if: always()
        env:
          ALLURE_REPORT_URL: ${{ needs.call-common-workflow.outputs.REPORT_URL }}
        run: |
          AI_SUMMARY=$(cat ai_analysis_result.json)
          echo -e "Cześć,\n\nPodsumowanie analizy AI:\n$AI_SUMMARY\n\nZobacz raport Allure: $ALLURE_REPORT_URL" | mail -s "AI Test Analysis + Allure report" adresat@example.com
